services:
  gitea:
    image: gitea/gitea:latest
    environment:
      - USER_UID=1001
      - USER_GID=1001
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=db:5432
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=${PASSWORD}
      # - GITEA__service__DISABLE_REGISTRATION=true
      - GITEA__server__ROOT_URL=https://git.rwillia.ms/
    restart: always
    volumes:
      - git_data:/data
    ports:
      - 3232:3000
      - 3222:22
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=gitea
      - POSTGRES_PASSWORD=${PASSWORD}
      - POSTGRES_DB=gitea
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    expose:
      - 5432
volumes:
  db_data:
  git_data:
